
FROM node:lts-alpine
WORKDIR /app
COPY . .
COPY package*.json ./
COPY prisma ./prisma/
RUN apk add --no-cache libc6-compat git openssl
RUN npm install
RUN npm install @prisma/client
COPY . .
RUN npx prisma generate --schema ./prisma/schema.prisma
RUN npm run build
EXPOSE 3000
CMD npm run start
